### ISSUE TITLE
Suggestion: creating a template repository including only the Spotify API 

### ISSUE THREAD

**Issue by VianaSamuel** [guilyx/guilyx#20]
Hey!
I loved your README template.
I'm a novice programmer and I tried (unsuccessfully) to fork your entire repository only to get the Spotify API.
I did all steps right, but the README was exactly like yours.
Would it be too much to ask you, if possible, to create a separate repository dedicated only to the Spotify API?
I found the tutorial a little complex for me, since I'm a novice on GitHub.
Thanks in advance!

**Comment by gavinmasese** [comment]
tutorial???which tutorial

**Comment by VianaSamuel** [comment]
> tutorial???which tutorial

The [HOW-TO.md](https://github.com/guilyx/guilyx/blob/master/HOW-TO.md).

**Comment by gavinmasese** [comment]
Gracias 
lemme check it out

**Comment by guilyx** [comment]
I'm so sorry guys I never got notifications for this!
Thanks @VianaSamuel for helping him/her out 😄

**Comment by guilyx** [comment]
@gavinmasese did you figure it out ?

**Comment by guilyx** [comment]
@VianaSamuel the Spotify API already has a seperate repo, it's the one from [here](https://github.com/andyruwruw/enhanced-spotify-api) I think.
If you still need help I can answer your questions now that I've seen it
Sorry for the delay

**Comment by gavinmasese** [comment]
> @gavinmasese did you figure it out ?
no sir
