### ISSUE TITLE
Cant build in vercel

### ISSUE THREAD

**Issue by Crushoverride007** [guilyx/guilyx#22]
I followed each step, but still there's an error in the build phase of vercel, do you know a fix?
<img width="608" alt="Screenshot 2022-07-16 at 02 00 04" src="https://user-images.githubusercontent.com/45631812/179328157-5e24c8b4-9ca4-4365-ad19-9afcabe69904.png">

**Comment by guilyx** [comment]
Mhhh, do you have a link to the repo you're building ?
