### ISSUE TITLE
404 Error: Page Not Found (Issue ID: bom1::9s5zb-1691534753225-54edf66a8d4d)

### ISSUE THREAD

**Issue by al3sha9** [guilyx/guilyx#31]
Issue Type: Bug | Status: Open | Severity: High

Description:
 encountering a "404: NOT_FOUND" error (Issue ID: bom1::9s5zb-1691534753225-54edf66a8d4d) when attempting to access a specific page. This issue is negatively impacting user experience as the requested page fails to load.

Steps to Reproduce:

Go to homepage.
Click link to problematic page.
Observe "404: NOT_FOUND" error.
Expected Behavior:
The page should load without errors.

Actual Behavior:
Users are greeted with a "404: NOT_FOUND" error, indicating the page cannot be located.

Additional Information:

Issue isolated to one page.
Error code "NOT_FOUND" suggests server resource issue.
Error ID "bom1::9s5zb-1691534753225-54edf66a8d4d" for debugging.
Impact:
Urgent attention needed due to poor user experience and engagement.

Proposed Solution:

Investigate cause of "404: NOT_FOUND" error.
Review server logs for context.
Verify URL routing configuration.
Ensure correct deployment of page and resources.
Implement user-friendly error handling.
Attachments: Error screenshots, relevant code snippets.

Note: Address this high-severity bug promptly to enhance user satisfaction.

**Comment by guilyx** [comment]
Shouldn't happen with new spotify snippet :-)

**Comment by al3sha9** [comment]
thanks for the help
